### ISSUE TITLE
Error on installing on swift 3

### ISSUE THREAD

**Issue by albarq** [prolificinteractive/Caishen#106]
Hi,

I tried my best before posting my answer here ... but still did not work ..

pod 'Caishen', :git => 'https://github.com/prolificinteractive/Caishen.git', :branch => 'swift-3.0'

but I receive this error:
[!] Error installing Caishen
[!] /usr/bin/git clone https://github.com/prolificinteractive/Caishen.git /var/folders/3f/hlddm2z55_91b6hx68g2vflw0000gn/T/d20161229-86999-1vt21f1 --template= --single-branch --depth 1 --branch swift-3.0

Cloning into '/var/folders/3f/hlddm2z55_91b6hx68g2vflw0000gn/T/d20161229-86999-1vt21f1'...
warning: Could not find remote branch swift-3.0 to clone.
fatal: Remote branch swift-3.0 not found in upstream origin

**Comment by DannyVancura** [comment]
Hi,
The branch you are pointing to (swift-3.0) has been merged and deleted, which is why cocoapods cannot install it with `pod 'Caishen', :git => 'https://github.com/prolificinteractive/Caishen.git', :branch => 'swift-3.0'` anymore. You can use `pod 'Caishen', '2.0.1'` now and it should work.

**Comment by albarq** [comment]
[!] Unable to satisfy the following requirements:

- `Caishen (= 2.0.1)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Caishen (= 2.0.1)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by DannyVancura** [comment]
Right, you'll need to run `pod repo update` before `pod install` in this case. Your local Cocoapods repo is outdated and it can't find this new version of Caishen. `pod repo update` should fix this.

**Comment by albarq** [comment]
thank you ... I am running  and it takes time
