### ISSUE TITLE
new to library

### ISSUE THREAD

**Issue by Nathan187** [prolificinteractive/Caishen#108]
i'm writing an app using swift 3

i added this framework to my project using carthage.  everything appears to be fine.  
however in interface builder, i can't set the class to CardTextField

I get an error when running the application
 Unknown class CardTextField in Interface Builder file

any help would be appreciated

**Comment by DannyVancura** [comment]
Hi, thanks for filing this issue.

The only reason I can think of for this is that the module hasn't been specified (see attached screenshot).

<img width="1068" alt="cardtextfield interface builder" src="https://cloud.githubusercontent.com/assets/15171764/23416569/a5cf8a72-fde3-11e6-9280-b1e2296c02a2.png">

Hope this helps!

**Comment by Nathan187** [comment]
Daniel, I'm sorry to waste your time.  I was able to get it to work. I should have closed it earlier.  Thank you so much

**Comment by DannyVancura** [comment]
Hey, no problem. Glad it works! If there's any information that could have helped you and that you think might be missing in the Readme, please let me know!
