### ISSUE TITLE
CardNumberFormatter Regex Broken

### ISSUE THREAD

**Issue by steven-diaz** [prolificinteractive/Caishen#110]
Example, American Express, debug output with a card number of "37671234561234"

CardType: AmericanExpress(name: "Amex", CVCLength: 4, numberGrouping: [4, 6, 5], identifyingDigits: Set([37, 34])), groups: [4, 6, 5]
Pattern: (\d{1,4})(\d{1,6})?(\d{1,5})?
Regex: <NSRegularExpression: 0x13772f8d0> (\d{1,4})(\d{1,6})?(\d{1,5})? 0x0
**Formatted: 3767 1234 5612 34**

**Comment by DannyVancura** [comment]
<img width="319" alt="screen shot 2017-06-09 at 3 32 40 pm" src="https://user-images.githubusercontent.com/15171764/26977692-161144da-4d29-11e7-8864-98ef189e7934.png">

Hey, this card number seems to be formatted correctly on my end (besides the fact that it is one digit too short to be valid).
