### ISSUE TITLE
xcode 9 beta 4 Build failed pod

### ISSUE THREAD

**Issue by feemi** [prolificinteractive/Caishen#114]
StringExtension.swift

```
    func NSRangeFrom(_ range : Range<String.Index>) -> NSRange {
        let utf16view = self.utf16
        let from = String.UTF16View.Index(range.lowerBound, within: utf16view)
        let to = String.UTF16View.Index(range.upperBound, within: utf16view)
        return NSMakeRange(utf16view.startIndex.distance(to: from), from.distance(to: to))
    }
```
` NSMakeRange(utf16view.startIndex.distance(to: from), from.distance(to: to))`
Value of optional type 'String.UTF16View.Index?' (aka 'Optional<String.Index>') not unwrapped; did you mean to use '!' or '?'?

**Comment by steven-diaz** [comment]
Yes, please address before Swift 3.2 goes live. Thanks!

**Comment by DannyVancura** [comment]
Hi, I created a [Swift 3.2](https://github.com/prolificinteractive/Caishen/tree/swift-3.2) branch for this (using current Xcode 9 Beta 5). I noticed an issue with both Swift 3.2 as well as [Swift 4.0](https://github.com/prolificinteractive/Caishen/tree/swift-4):

When you open the view controller containing a card text field and closing it again (without entering text in the text field), the app crashes after the view was dismissed. Not so, if you enter something in the text field prior to closing the view. In this case no crashes occur.
Unfortunately I wasn't able to get any error about why this is failing yet and am still investigating.

**Comment by piercifani** [comment]
Any news?

**Comment by walterhuangfs** [comment]
I'm seeing this with XCode 9 as well.

**Comment by zahedul** [comment]
<img width="996" alt="screen shot 2017-10-20 at 6 05 34 am" src="https://user-images.githubusercontent.com/1929044/31799602-d63990c8-b55c-11e7-84be-4adbfc854436.png">

Using Xcode 9. couldn't run

**Comment by DannyVancura** [comment]
The Swift 4 branch has been merged and the current version supports Swift 4.
