### ISSUE TITLE
Customizable credit card image insets

### ISSUE THREAD

**Issue by MichaelCampbell** [prolificinteractive/Caishen#12]
Is there a way to customize the credit card image insets?

![custom credit card image insets](https://www.dropbox.com/s/v20uieiygel00i8/Simulator%20Screen%20Shot%20Mar%2024%2C%202016%2C%206.01.51%20PM%20custom%20image%20insets.png?raw=1)

**Comment by DannyVancura** [comment]
Added a PR to address this request: [#22](https://github.com/prolificinteractive/Caishen/pull/22)

**Comment by DannyVancura** [comment]
Closing this issue, since [it's solved.](https://github.com/prolificinteractive/Caishen/pull/22#issuecomment-205868296)
