### ISSUE TITLE
Can't type anything into the custom TextFields.

### ISSUE THREAD

**Issue by teo029** [prolificinteractive/Caishen#125]
I just set my TextFields to correspond to the examples (e.g. CVCInputTextField) and when I try to type inside those, nothing happens (cursor doesn't move and I can't see the text). Moreover, the keyboard doesn't change to the corresponding input type. 

If I try to type something in other non-custom Text Fields inside my UI, it works.

**Comment by teo029** [comment]
Yeah, seems like the problem was not really a problem. It just doesn't allow you to type in non-numerical characters. 

You guys should've posted a error-ish border for the field or something or maybe change the input type programatically.

Solved.

**Comment by ppatriotis** [comment]
Sounds like a good idea! Any chance you have a PR of that change you'd like to submit?

**Comment by DannyVancura** [comment]
Since you mentioned this issue is solved for you, I'm gonna close this issue. As @ppatriotis mentioned: If you happen to implement said error-ish border, please feel free to create a PR for this, so we can consider this for a future version. Thanks!
