### ISSUE TITLE
Support new BIN ranges for MasterCard

### ISSUE THREAD

**Issue by hkellaway** [prolificinteractive/Caishen#137]
MasterCard just introduced new BIN ranges. Caishen should be able to recognize new ranges as a MasterCard

https://www.cardfellow.com/new-mastercard-bins/

**Comment by hkellaway** [comment]
MasterCard page out it: https://www.mastercard.us/en-us/issuers/get-support/2-series-bin-expansion.html

**Comment by hkellaway** [comment]
example numbers that should be recognized as MasterCard:
2221-1111-1111-1112
2221-1112-2222-2204

**Comment by DannyVancura** [comment]
@hkellaway is [this](https://github.com/prolificinteractive/Caishen/pull/134) related? if so, this has been released with [version 2.1.1](https://github.com/prolificinteractive/Caishen/releases/tag/2.1.1).
