### ISSUE TITLE
Swift 5 update

### ISSUE THREAD

**Issue by hkellaway** [prolificinteractive/Caishen#150]

**Comment by hkellaway** [comment]
i have a branch named `swift5` working here: https://github.com/prolificinteractive/Caishen/tree/swift5

current issue is the Gemfile relies on CocoaPods version `1.7.0.beta.3` - should wait until `1.7.0` is stable then update the Gemfile

**Comment by HardikDG** [comment]
Any update on Swift 5 support for this library?

**Comment by hkellaway** [comment]
I’ll not personally be finishing this PR. The owning org (prolificinteractive) was acquired; the acquirer may or may not have a maintenance strategy, I don’t know myself. 

If needed in the immediate, I’d create a fork
