### ISSUE TITLE
Have Expiry class handle MM/YY format

### ISSUE THREAD

**Issue by ThibaultKlein** [prolificinteractive/Caishen#2]
Currently the Expiry class needs a `MM/YYYY` format, can we have it handle `MM/YY`?

**Comment by Haud** [comment]
Can you elaborate?

**Comment by ThibaultKlein** [comment]
In Expiry class the convenient init says:

```
/**
     Creates a `CardExpiry` with the given string.
     - parameter string: A string of the form MM/YYYY.
*/
public convenience init?(string: String)
```

I want to pass a `MM/YY` format instead.

**Comment by Haud** [comment]
Check out my PR which releats to refactoring Expiry: 

https://github.com/prolificinteractive/Caishen/pull/1

You should be able to pass in a two-digit number and it will automatically parse it out.

**Comment by Haud** [comment]
@ThibaultKlein This format should be handled. Our unit tests cover the case of `MM/yy`. Can you give me an example or something not working?

**Comment by ThibaultKlein** [comment]
I just read the code and didn't find `MM/YY` in the documentation which is why I created this issue. If your unit tests cover this format you can close this issue. :+1:
