### ISSUE TITLE
The tappable area in a CardNumberTextField is too small to tap into

### ISSUE THREAD

**Issue by MichaelCampbell** [prolificinteractive/Caishen#3]
To Reproduce:
> To add a text field for entering card information to a view, either ...

> - ... add a UITextField to your view in InterfaceBuilder and change its class to *CardNumberTextField* (when using InterfaceBuilder)

If you try to tap into the CardNumberTextField, the tap area is too small. You have to tap right beside the card image (probably less than 10 points away) to get it working.

**Comment by DannyVancura** [comment]
Thanks! That's indeed a bug when missing a placeholder. [This PR](https://github.com/prolificinteractive/Caishen/pull/5) should fix it.

**Comment by MichaelCampbell** [comment]
It does, thanks!
