### ISSUE TITLE
Add support for SPM

### ISSUE THREAD

**Issue by hkellaway** [prolificinteractive/Caishen#40]

**Comment by hkellaway** [comment]
Let me know if someone has already started or will start this - otherwise I'll go at it

**Comment by hkellaway** [comment]
we can reopen when SPM supports ios

**Comment by gomera** [comment]
@hkellaway any plans on adding spm support now?

**Comment by hkellaway** [comment]
@gomera not specifically. the agency that created this project was acquired in 2019 and development on open source stopped. i'd suggest forking it and adding SPM support
