### ISSUE TITLE
Random background image around card

### ISSUE THREAD

**Issue by MichaelCampbell** [prolificinteractive/Caishen#42]
There appears to be a random shadow image around the credit card. 
![background image](https://www.dropbox.com/s/huiyjenw18l0oog/Screenshot%202016-04-07%2018.35.25.png?raw=1)

This may be related to #12

**Comment by DannyVancura** [comment]
Thanks for pointing that out - didn't notice that yet!
When you set the text field's background color, this color will currently also be set for the image view's background. The image view itself got a shadow in #35 which is what you see here as the shadow is drawn below this white layer.
This gets problematic, especially when the view constraints are changed to inset the image view ( #12 ), as the image view's size changes. I'll fix it asap.

Thanks!
