### ISSUE TITLE
Language support RTL?

### ISSUE THREAD

**Issue by mohammad19991** [prolificinteractive/Caishen#48]

**Comment by DannyVancura** [comment]
Hi, thank you for pointing this out! To support RTL languages properly, do the following changes sound sufficient?
- Show the card type image on the right of the text field
- Show the card number (right-aligned) next to the card image
- When the number has been entered, shrink the text field to display only the last four digits to the left of the card type image and slide in [CVC , YY/MM] from the left
- Show the optional accessory button on the left side of the view

**Comment by mohammad19991** [comment]
it is sufficient, image should be on the right and text entry starts from right to left.

**Comment by DannyVancura** [comment]
I added a PR to tackle this issue: #50

**Comment by mohammad19991** [comment]
@DannyVancura thanks

**Comment by DannyVancura** [comment]
Closing with #50: RTL language support is now available with version 1.2.2
