### ISSUE TITLE
Caishen - IQKeyboardManagerSwift

### ISSUE THREAD

**Issue by MichaelCampbell** [prolificinteractive/Caishen#52]
Currently, I am using Caishen and IQKeyboardManager to move between text fields on a custom payment view screen. Generally it works pretty well, but for some reason i can’t get it to work when moving from a regular `UITextField` to a `CardTextField`, and vice versa.

Based on a quick glance, it appears that `CardTextField` rejects `becomeFirstResponder. Is it possible for someone to take a look?

**Comment by DannyVancura** [comment]
I added a PR to make a `CardTextField` selectable via IQKeyboardManager: #53 

`CardTextField` itself contains subviews, which still causes one problem: Only text fields within a single view are considered by IQKeyboardManager, meaning that you can only switch back and forth between the subviews of `CardTextField`, but not the ones outside of it for example.
So stepping in and out of a `CardTextField` still requires a few lines in your code (for example in `viewDidLoad`):

```swift
cardNumberTextField.addPreviousNextDoneOnKeyboardWithTarget(self, previousAction: #selector(self.selectPrevious), nextAction: #selector(self.selectNext), doneAction: #selector(self.done))
```

The functions `selectPrevious`, `selectNext` and `done` in this case should call `becomeFirstResponder` or `resignFirstResponder` as intended:

```swift
...

func selectNext() {
    textFieldAfterCardTextField.becomeFirstResponder()
}

...
```

Can you check this out and see if it fixes your problem?
