### ISSUE TITLE
China Union Pay card number validation not working

### ISSUE THREAD

**Issue by ThibaultKlein** [prolificinteractive/Caishen#54]
Hey,

I tried to use a China Union Pay credit card number but Caishen keeps telling me it's an invalid number. Here is the number I used: 6240008631401148
Source: https://support.cybersource.com/cybskb/index?page=content&id=C1357&actp=RSS

Could you test on your end and let me know if you are experiencing the same issue? 
I'm using Caishen 1.1.0.

Thanks!

**Comment by DannyVancura** [comment]
Hi,
The PR for this was merged post 1.1.0.
China Union Pay is now available in version 1.2.0!
