### ISSUE TITLE
Allow to disable Luhn test for a custom card type

### ISSUE THREAD

**Issue by ThibaultKlein** [prolificinteractive/Caishen#56]
Hi,
Would it be possible to have the option to disable Luhn test in a custom card type? Some cards don't require this validation but Caishen doesn't allow this functionality currently.

I would suggest to create a boolean in `CardType` that is checked before Luhn test is applied.

Thanks!

**Comment by DannyVancura** [comment]
Hi,
`CardType` contains the method `public func validateNumber(cardNumber: Number)` which has a default implementation in a protocol extension:

```swift
    public func validateNumber(cardNumber: Number) -> CardValidationResult {
        return lengthMatchesType(cardNumber.length)
            .union(numberIsNumeric(cardNumber))
            .union(numberIsValidLuhn(cardNumber))
    }
```

If you implement this for your card type without the Luhn test, it should work:

```swift
    public func validateNumber(cardNumber: Number) -> CardValidationResult {
        return lengthMatchesType(cardNumber.length)
            .union(numberIsNumeric(cardNumber))
    }
```

**Comment by ThibaultKlein** [comment]
Hey @DannyVancura,

Unfortunately, `lengthMatchesType` and `numberIsNumeric` are internal functions and I can't use them.

**Comment by DannyVancura** [comment]
Oh, my bad. I'll create a PR to make these available publicly.

**Comment by DannyVancura** [comment]
Here is the PR for this: #57 
If you need any other methods available for this issue, please let me know.
I would apply the changes with the next Patch version.

Thanks,
Daniel

**Comment by ThibaultKlein** [comment]
I tried your pull request and it's working for me 👍
