### ISSUE TITLE
Demo project Buy Now does nothing

### ISSUE THREAD

**Issue by ThibaultKlein** [prolificinteractive/Caishen#62]
Hi,

When tapping on the Buy Now button nothing happens and the console prints this error:

```
<UIVisualEffectView 0x7cb68040> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.
```

A quick fix to unblock the QA is to change the background color to white in `Main.storyboard`.

Thanks!

**Comment by kishykumar** [comment]
Yes, it didn't work for me too (on iOS 9). But, it did work on iOS 8.

**Comment by DannyVancura** [comment]
Closing this - this issue seems to be gone with the current version. Please feel free to reopen the issue if you still encounter it.
