### ISSUE TITLE
navigation popviewcontroller fires translateCardNumberIn() and crashes

### ISSUE THREAD

**Issue by atlcodecommandr** [prolificinteractive/Caishen#66]
Hello, 
For some reason when I click cancel or pop the viewcontroller that caishen is in, it crashes on the line:
  
let offset = isRightToLeftLanguage ? -superview!.bounds.width : superview!.bounds.width

Any Idea what it could be?

**Comment by DannyVancura** [comment]
Hey @atlcodecommandr , thank you for your bug report!
I wasn't able to reproduce this error on my end, but I assume the crash occurs because of the force unwrap of a missing `superview`.

Can you please have a look at PR #67 and let me know if that fixes the problem in your view?

Thanks,
Daniel

**Comment by everhardt** [comment]
I checked: PR #67 solves it.
