### ISSUE TITLE
is it possible to use Caishen components separately

### ISSUE THREAD

**Issue by mohammad19991** [prolificinteractive/Caishen#68]
I have different design from what Caishen provide right now and I wanna check if I can use the textFields separately and take advantage of the current component because it provides complete solution regarding the validation, support different card types... etc
Thank you!

**Comment by DannyVancura** [comment]
Hey!

Thank you for the issue! Right now, some of the properties to make this work are marked as internal. I created a PR ( #70 ) to change these and added a very basic example to the Readme to show how this can be done.
Please let me know if the readme is descriptive enough or if you are missing any details in it!

Thanks,
Daniel

**Comment by mohammad19991** [comment]
@DannyVancura hey! any updates? check my comment on PR #70.
