### ISSUE TITLE
Can't get CardTextField to not be first responder

### ISSUE THREAD

**Issue by kishyr** [prolificinteractive/Caishen#69]
Hi

Thanks for the great project!

By default, my CardTextField object becomes the first responder and I can't seem to disable that feature. I've tried calling `resignFirstResponder()` on it, but it doesn't seem to work. How can I make it not be the first responder in the first place?

Thanks!

**Comment by DannyVancura** [comment]
Hi,

Thanks for the bug report! Which version of Caishen do you use?
This bug was a known issue in version 1.2.2 but PR #65 should have fixed this problem for version 1.2.3.

Best regards,
Daniel

**Comment by kishyr** [comment]
Ah! I didn't realise there was a new version out. I was still on 1.2.2. It does look like it's fixed 1.2.3. Thanks so much, and thanks again for the great project!
