### ISSUE TITLE
CardNumberTextField delegate not passing CardValidationResult until all fields are filled

### ISSUE THREAD

**Issue by MichaelCampbell** [prolificinteractive/Caishen#7]
In the delegate function:
```
func cardNumberTextField(cardNumberTextField: CardNumberTextField,
                             didEnterCardInformation information: Card?,
                                                     withValidationResult validationResult: CardValidationResult?)
```
the CardValidationResult is only set once the CC number, expiration date and CVC code are set. The expected result is that the CardValidationResult will raise issues as they come up with every keystroke.

For example, if i am entering a CC number and enter 1111-11, on the next tap of 1, I expect that CardValidationResult will not be nil, because the text color changes to red, hinting that there is a validation issue.

**Comment by Haud** [comment]
Please see #9 for a fix.

**Comment by MichaelCampbell** [comment]
works well, thanks for the fix
