### ISSUE TITLE
Manual installation

### ISSUE THREAD

**Issue by ElectrumDevelopment** [prolificinteractive/Caishen#77]
I installed it, how do I get the individual pieces as string so I can set it to user defaults

**Comment by ElectrumDevelopment** [comment]
func cardTextField(cardTextField: CardTextField, didEnterCardInformation information: Card, withValidationResult validationResult: CardValidationResult) {
        if validationResult == .Valid {
            defaults.setObject(Card.Number, forKey: "cardNumber")
            defaults.setObject(Card.expiryDate, forKey: "expDate")
            defaults.setObject(Card.cardVerificationCode, forKey: "cvc")

        }
    }

Thats how I have it and it doesn't work

**Comment by DannyVancura** [comment]
Hey,
I think saving the pieces to user defaults should look more like this:

```swift
defaults.setObject(information.bankCardNumber.rawValue, forKey: "number")
defaults.setObject(information.expiryDate.rawValue, forKey: "expiry")
defaults.setObject(information.cardVerificationCode.rawValue, forKey: "cvc")
```

Depending on your use case I'd probably not save the CVC or even the data all together. At least the PCI security standards council [advises to store data only if necessary and not to store the CVC at all](https://www.pcisecuritystandards.org/pdfs/pci_fs_data_storage.pdf).

Also I'd recommend to encrypt the data. NSUserDefaults is basically stored as a plain plist file, potentially exposing the user's credit card information. I would use [Keychain Services](https://developer.apple.com/library/ios/documentation/Security/Conceptual/keychainServConcepts/01introduction/introduction.html) for this use case.

**Comment by ElectrumDevelopment** [comment]
Thanks for the suggestions! Encryption will definitely be my first priority

**Comment by ElectrumDevelopment** [comment]
Also, any way to capture the date as a string instead of a NSDate?

**Comment by DannyVancura** [comment]
To get a date in any form you want, you should use an NSDateFormatter, possibly in the language that the device user uses and with the date and time format that you need (like `Jan 1, 2016`, `1/1/2016`, etc.).
