### ISSUE TITLE
CardValidationResult { } characters in description

### ISSUE THREAD

**Issue by MichaelCampbell** [prolificinteractive/Caishen#8]
Currently there is no way to get plain text error messages from a `CardValidationResult`. The results are put into a JSON like structure, as seen in the following image.

![Card Validation Result](https://www.dropbox.com/s/x6y3icf37m2w4ql/Screenshot%202016-03-23%2012.34.54.png?raw=1)

Would it be possible to have a function or property that returns an array of strings, or update `description` to remove the `{` `\t` and `}` characters, and the initial new line character?

**Comment by Haud** [comment]
Please see #9 for a fix.

**Comment by MichaelCampbell** [comment]
works well, thanks for the fix
