### ISSUE TITLE
NumberInputTextField text color not working with prefillInformation

### ISSUE THREAD

**Issue by josalmi** [prolificinteractive/Caishen#80]
I'm having problems setting textColor to `NumberInputTextField` when using with `prefillInformation` with Card.IO integration. I used very hacky workaround for this:

`cardNumberInput.textField(cardNumberInput, shouldChangeCharactersInRange: NSMakeRange(0, cardNumberInput.text!.characters.count), replacementString: cardNumberInput.text!)` 

I guess there is a bigger issue behind this caused by the use of `_textColor` because this seemed to be to only way to trigger `super.textColor` change.

**Comment by ppatriotis** [comment]
I'm sorry it's been a while, the maintainer @DannyVancura has been busy with a rollout the past 2 weeks. Hope we can get this answered in a week or two. If you have any ideas about how to fix this in a non-hacky way in the meantime, feel free to submit a pull request.

**Comment by DannyVancura** [comment]
Hi,
thanks for filing this issue and posting the workaround. The way your workaround handles text input makes sense to me, as it treats pre-filled information like user input. #94 should fix this issue.
