### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by havocked** [prolificinteractive/Caishen#83]
Hello ! I Really appreciate your work guys. Is there any chances to know when you will release swift 3 compatibility ?

**Comment by ppatriotis** [comment]
Sorry, we've been busy with a rollout, so we'll probably be able to get to it in a week. In the meantime pls feel free to try / debug / fix https://github.com/prolificinteractive/Caishen/pull/79

**Comment by borut-t** [comment]
+1

**Comment by jackpaster** [comment]
+1 you said in a week. Its october now

**Comment by jackpaster** [comment]
could you please get it updated

**Comment by jackpaster** [comment]
I love the work you guys do, by the way. This project is amazing

**Comment by DannyVancura** [comment]
Hi, I'm very sorry about the delay. We have a PR pending to add Swift 3 compatibility [here](https://github.com/prolificinteractive/Caishen/pull/85). Since this introduces a significant amount of changes to the public API that cannot easily be fixed later we'd rather not merge this without some more reviews on it. Please feel free to take a look at those changes and share your feedback.

**Comment by jackpaster** [comment]
so i'm confused, will you update the project to swift 3.0

**Comment by jackpaster** [comment]
@prolificInteractive so i'm confused, will you update the project to swift 3.0

**Comment by jackpaster** [comment]
When I open the project in xcode 8, swift 3.0, I get numerous errors and that the cocoapods are out of date

**Comment by jackpaster** [comment]
I spent hours trying to fix it but was led nowhere

**Comment by DannyVancura** [comment]
Yes, we will update the project to Swift 3 eventually. Are you working on this PR: #85 ? The one mentioned above (#79) is outdated, since it was created on Xcode 8 beta and Apple made changes to the Swift 3 API since then. Which version of Cocoapods are you using?

**Comment by jackpaster** [comment]
the latest version

**Comment by jackpaster** [comment]
do you know when you will update the project. I need a credit card
validation system for my app. And this is the by far the best one ive seen
on github, etc. But I cant use it

**Comment by jackpaster** [comment]
@prolificInteractive do you know when you will update the project. I need a credit card
validation system for my app. And this is the by far the best one ive seen
on github, etc. But I cant use it

**Comment by jackpaster** [comment]
is there a possibility it can be updated next week.

**Comment by DannyVancura** [comment]
I think next week does sound realistic. In the meantime you should be able to use the current Swift 3 branch by adding `pod 'Caishen', :git => 'git@github.com:prolificinteractive/Caishen.git', :branch => 'swift-3.0'` to your Podfile.

**Comment by jackpaster** [comment]
ok ill do it and get back to you, but i'm begging you guys to please update
it. All I have left in my app is a creditcard validation system. Thats why
I'm so desperate.

**Comment by jackpaster** [comment]
@ProlificInteractive ok ill do it and get back to you, but i'm begging you guys to please update it. All I have left in my app is a creditcard validation system. Thats why I'm so desperate.

**Comment by gustavoamgarten** [comment]
Hey guys, how is this going? I tried adding `pod 'Caishen', :git => 'git@github.com:prolificinteractive/Caishen.git', :branch => 'swift-3.0'` but it didn't work out, as I got an error on `pod install`.

**Comment by DannyVancura** [comment]
What is the error you got? My guess is that you may not have ssh keys set up to use the command as posted. If so, this command should work for you: `pod 'Caishen', :git => 'https://github.com/prolificinteractive/Caishen.git', :branch => 'swift-3.0'`
Or optionally, set up an SSH key for your computer on Github [as described here](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/).

**Comment by jackpaster** [comment]
I successfully added the pods, but I get a swift binary issue. Now I tried changing swift legacy, but then I got 800+ errors in my project. Heres an image of the error. 
<img width="987" alt="screen shot 2016-10-21 at 7 40 21 pm" src="https://cloud.githubusercontent.com/assets/17861785/19614753/38a34354-97c6-11e6-9b5a-ce29d3e657b8.png">

**Comment by DannyVancura** [comment]
Swift Legacy should be set to `NO` for a Swift 3.0 project. On Cocoapods version 1.0.x you'd have to add the following to the Podfile to set this properly for Cocoapods dependencies:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
	config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

In version 1.1.x (pre-release clients) you'd have to add a file called `.swift-version` in the same folder as your Podfile that only contains the text `3.0`.

The following worked for me in a small example project with Cocoapods version 1.0.1:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'CaishenTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Caishen', :git => 'https://github.com/prolificinteractive/Caishen.git', :branch => 'swift-3.0'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end

end
```

**Comment by jackpaster** [comment]
i'm confused on what to do, i'm trying it but it keeps telling me to fix all the syntax errors to transfer the code from 2.3 to 3.0

**Comment by jackpaster** [comment]
I did what you said and the amount of syntax error I received was well over 100+. I fixed half of them but I've been stuck for three days now. Can you please help

**Comment by jackpaster** [comment]
Here are images. 

<img width="465" alt="screen shot 2016-10-21 at 10 35 00 pm" src="https://cloud.githubusercontent.com/assets/17861785/19616335/a69a35bc-97de-11e6-8913-d402bf866d0b.png">
![Uploading Screen Shot 2016-10-21 at 10.34.55 PM.png…]()
![Uploading Screen Shot 2016-10-21 at 10.34.47 PM.png…]()
![Uploading Screen Shot 2016-10-21 at 10.34.43 PM.png…]()

**Comment by jackpaster** [comment]
<img width="279" alt="screen shot 2016-10-21 at 10 34 43 pm" src="https://cloud.githubusercontent.com/assets/17861785/19616351/b71d7610-97de-11e6-9a23-e0ca46d7d0dd.png">

**Comment by jackpaster** [comment]
Could you update the project please

**Comment by jackpaster** [comment]
I spent three days fixing 400 errors and upgrading the project to swift 3.0. I'm left with 25 that i don't know how to fix and i'm hoping you can help

**Comment by jackpaster** [comment]
Ill send you the updated project. I fixed most of the errors, but could you finish the tiny bit left

**Comment by DannyVancura** [comment]
I'm sorry, but it doesn't look like you are working with branch `swift-3.0`. If you look at the implementation of `isFirstResponder` [here](https://github.com/prolificinteractive/Caishen/blob/swift-3.0/Pod/Classes/UI/CardTextField.swift) for example (line 195) you will see the code difference to the screenshot you posted above.

**Comment by ppatriotis** [comment]
@jackpaster we are working on the Swift 3.0 update, but it's a major change so it won't be out for at least a few weeks. I understand you need it for your project, and there is a working version if you follow @DannyVancura 's instructions carefully, we just will not make an official release until it's stable.

**Comment by jackpaster** [comment]
Here is some code how can I fix this. Its a nslocale error. 

internal var isRightToLeftLanguage: Bool {
        if #available(iOS 9.0, *) {
            return UIView.userInterfaceLayoutDirection(for: semanticContentAttribute) == .rightToLeft
        } else {
            let locale = Locale.current
            let isoCode = Locale.autoupdatingCurrent.object(forkey: NSLocaleLanguageCode) as? String ?? ""
            return NSLocale.characterDirectionForLanguage(isoCode) == NSLocaleLanguageDirection.RightToLeft
        }
    }

I get an error at:  let isoCode = Locale.autoupdatingCurrent.object(forkey: NSLocaleLanguageCode) as? String ?? ""

Here is an image
<img width="1198" alt="screen shot 2016-10-22 at 5 40 19 pm" src="https://cloud.githubusercontent.com/assets/17861785/19622732/dacd3df2-987e-11e6-916b-3aba0501498c.png">

**Comment by jackpaster** [comment]
@DannyVancura 
@ppatriotis 

Do you have a suggestion to fix this

**Comment by DannyVancura** [comment]
The code on the branch `swift-3.0` looks different here:

```swift
let isoCode = Locale.autoupdatingCurrent.languageCode ?? ""
return Locale.characterDirection(forLanguage: isoCode) == Locale.LanguageDirection.rightToLeft
```

To fix this: Running `pod install` again with the Podfile set up as I mentioned [above](https://github.com/prolificinteractive/Caishen/issues/83#issuecomment-255495469) (meaning: use exactly this line to integrate Caishen: `pod 'Caishen', :git => 'https://github.com/prolificinteractive/Caishen.git', :branch => 'swift-3.0'`) should solve these issues. 

Side note: If you are working on this within your project, you should never have to touch the code base of Cocoapods libraries at all. Changes are lost whenever you run `pod install` and this code is usually not checked into project repositories.

**Comment by jackpaster** [comment]
Can you just please help me solve these two last errors. 

There this:

public func checkCardNumberPartiallyValid(cardNumber: Number) -> CardValidationResult {
        let validationResult = validateNumber(number: cardNumber)
        let completeNumberButLuhnTestFailed = !validationResult.isSuperset(of: CardValidationResult.NumberIncomplete) && validationResult.isSuperset(of: CardValidationResult.LuhnTestFailed)

        if completeNumberButLuhnTestFailed {
            return validationResult
        } else {
            return
                self.validateNumber(number: cardNumber)
                    .subtract(.NumberIncomplete)
                    .subtract(.LuhnTestFailed)
        }
    }

And I get an error at: self.validateNumber(number: cardNumber)

Here is an image of the error:

<img width="1187" alt="screen shot 2016-10-22 at 6 04 45 pm" src="https://cloud.githubusercontent.com/assets/17861785/19622848/0831f1c2-9882-11e6-93e9-668f0061b3a8.png">

**Comment by jackpaster** [comment]
@ppatriotis 
@DannyVancura 

Could you please fix this error. I'm not touching the cocoa pods. It's outdated swift 2.3 code i'm trying to fix that i will share with you. So that you guys don't have to put in all the work to solve this

**Comment by jackpaster** [comment]
I'm almost done and will send you guys an updated project, but I'd like a little help.

**Comment by jackpaster** [comment]
I fixed the code in the frameworks

**Comment by ppatriotis** [comment]
@jackpaster I'm confused, I thought you needed the Swift 3.0 version

**Comment by jackpaster** [comment]
Yes i do.

**Comment by jackpaster** [comment]
I'm going to send you the updated code

**Comment by jackpaster** [comment]
for swift 3.0

**Comment by ppatriotis** [comment]
@jackpaster the `swift-3.0` branch already has the updated code for swift 3.0

**Comment by ppatriotis** [comment]
There's no need to send

**Comment by jackpaster** [comment]
could you please help fix the issue. I'm about to solve my problem. I did that and I got a binary error. Could you please help me find an answer for the question above with the nslocale

**Comment by jackpaster** [comment]
@DannyVancura what would be your suggestion

**Comment by ppatriotis** [comment]
@jackpaster we published the workaround months ago. We do not have the ability to debug forked code. Please use the standard workarounds and fix it if possible. It will be quicker and help us make a more stable product for everyone.

**Comment by jackpaster** [comment]
could you tell me your suggestion for the nslocale though. I understand that you have fixes for the problem but what is your suggestion to fix the nslocale problem

**Comment by DannyVancura** [comment]
The code I posted for this above should work:

```swift
let isoCode = Locale.autoupdatingCurrent.languageCode ?? ""
return Locale.characterDirection(forLanguage: isoCode) == Locale.LanguageDirection.rightToLeft
```

**Comment by ppatriotis** [comment]
@jackpaster @DannyVancura if you guys would like to hop into a chat, go here: https://gitter.im/prolificinteractive/Caishen

**Comment by jackpaster** [comment]
I'm getting an import caishen error. No such module and the frameworks are there
