### ISSUE TITLE
card.io won't present app crashes

### ISSUE THREAD

**Issue by jackpaster** [prolificinteractive/Caishen#93]
The app crashes at this line
 let cardIOViewController = CardIOPaymentViewController(paymentDelegate: self)

It's not recognizing paymentdelegate

**Comment by DannyVancura** [comment]
Hi,
what is the crash report? Also, which branch are you working on?

**Comment by jackpaster** [comment]
So everything worked could we talk on the messenger so I can send you pictures

**Comment by jackpaster** [comment]
The crash report is 
<img width="488" alt="screen shot 2016-10-23 at 4 20 38 pm" src="https://cloud.githubusercontent.com/assets/17861785/19629179/ad42ee04-993c-11e6-8e31-2937aa67b628.png">

**Comment by jackpaster** [comment]
once I click on the credit card to take a picture, the app crashes

**Comment by jackpaster** [comment]
@DannyVancura what would be the fix

**Comment by DannyVancura** [comment]
That is not the full crash report. Please include line 1-31 as well.

**Comment by jackpaster** [comment]
ok

**Comment by jackpaster** [comment]
how do i get the crash report

**Comment by jackpaster** [comment]
<img width="475" alt="screen shot 2016-10-23 at 4 23 56 pm" src="https://cloud.githubusercontent.com/assets/17861785/19629205/1eaa19f0-993d-11e6-8b94-e386c45f7c2c.png">

**Comment by jackpaster** [comment]
@DannyVancura is this it

**Comment by jackpaster** [comment]
what would be the fix

**Comment by jackpaster** [comment]
@DannyVancura could you please help me resolve the issue

**Comment by DannyVancura** [comment]
Is this the unmodified example project from the Caishen repository that you are running? It seems that there is an issue with the project settings here. In fact, the error description even tells you what's wrong and how to solve it:
```
Terminating app due to uncaught exception 'CardIO-IncompleteIntegration', reason: 'Please add -ObjC to 'Other Linker Flags' in your project settings.
```

**Comment by jackpaster** [comment]
I removed -objc because i got this error after i ran pod install

<img width="898" alt="screen shot 2016-10-23 at 4 44 24 pm" src="https://cloud.githubusercontent.com/assets/17861785/19629310/08bdaece-9940-11e6-8e23-28986b197372.png">

**Comment by jackpaster** [comment]
@DannyVancura there were 2 duplicate symbols for architecture i386

**Comment by jackpaster** [comment]
what do you think might be the fix

**Comment by jackpaster** [comment]
can you help me

**Comment by jackpaster** [comment]
i did pod degenerate and did pod install and i came up with the same problem from yesterday

**Comment by DannyVancura** [comment]
[Cocoapods](https://github.com/CocoaPods/CocoaPods) and [CardIO](https://github.com/card-io/card.io-iOS-SDK) related issue. Please refer to respective repositories for details.
