### ISSUE TITLE
I can't change the card number separator

### ISSUE THREAD

**Issue by welove** [prolificinteractive/Caishen#95]
I can't change the card number separator.

i tried:
`cardTextField.numberInputTextField.cardNumberSeparator = "-"`
and:
`cardTextField.cardNumberSeparator = "-"`

i get the following error:
Thread 1: EXC_BAD_ACCESS
at CardNumberFormater.swift in public func format(cardNumber: String) -> String
on the following line:
regex = try NSRegularExpression(pattern: pattern, options: NSRegularExpression.Options())

**Comment by DannyVancura** [comment]
Hi @welove, thank you for reporting this issue!
I tried to reproduce this bug on the Example project but it didn't crash for me with the lines that you posted above. Can you to share more information about how you set up Caishen and what you did when you ran into this issue please?
Like:
- What placeholder text did you set and how did you set it?
- Did you pre-fill any card information before you ran into the issue?
- Did you set any parameters in the Storyboard file?
- ...

A code snippet of your setup for the text field would be best!

Thanks,
Daniel

**Comment by welove** [comment]
Hi Danny, here is full my code:

```
cardTextField = CardTextField(frame: CGRect(x: 15, y: 5, width: cardBgView.frame.size.width-30, height: 30))
cardTextField.placeholder = NSLocalizedString("New Credit Card", comment: "")
cardTextField.cardTextFieldDelegate = self
cardTextField.numberInputTextField.cardNumberSeparator = "-"
cardBgView.addSubview(cardTextField)
```

Just tested it out, and If i comment/delete the placeholder line, it works.
