### ISSUE TITLE
Card Number Text Field Not Responsive

### ISSUE THREAD

**Issue by sahil-a** [prolificinteractive/Caishen#96]
Once _all card info is entered_ and the cardNumberTextField is tapped (not swiped), the CardTextField will not transition back to the full cardNumberTextField mode or even allow editing of the card number.

**Comment by DannyVancura** [comment]
Hi @sahil-a,
Thanks for reporting this issue. Does this only happen for specific card types? And which branch or version of Caishen are you using? On master (version 1.4.0, Swift 2.3) I am unable to reproduce this issue.

**Comment by DannyVancura** [comment]
Unable to reproduce.
