### ISSUE TITLE
no pod spec found

### ISSUE THREAD

**Issue by jackpaster** [prolificinteractive/Caishen#99]
Can you help me. I'm trying to pod install but your pods are failing for me

**Comment by DannyVancura** [comment]
Hi,
can you please provide more information about what is failing?

**Comment by jorgelp94** [comment]
This is what I'm getting:
[!] Error installing Caishen
[!] /usr/bin/git clone https://github.com/prolificinteractive/caishen.git /var/folders/ch/1jpjny5s2bs0n5g5vjpjzkkm0000gn/T/d20161214-38038-vyfwn8 --template= --single-branch --depth 1 --branch 1.4.0

Cloning into '/var/folders/ch/1jpjny5s2bs0n5g5vjpjzkkm0000gn/T/d20161214-38038-vyfwn8'...
fatal: unable to access 'https://github.com/prolificinteractive/caishen.git/': Could not resolve host: github.com

**Comment by DannyVancura** [comment]
When running the exact same command I don't get this error:

```
git clone https://github.com/prolificinteractive/caishen.git ./test --template= --single-branch --depth 1 --branch 1.4.0
Cloning into './test'...
remote: Counting objects: 169, done.
remote: Compressing objects: 100% (159/159), done.
remote: Total 169 (delta 25), reused 89 (delta 3), pack-reused 0
Receiving objects: 100% (169/169), 810.42 KiB | 82.00 KiB/s, done.
Resolving deltas: 100% (25/25), done.
Checking connectivity... done.
Note: checking out '1307dbff77e61ea4e02d757acd8913ef55054a6d'.
```

**Comment by DannyVancura** [comment]
Cocoapods/Git related issue.
